version: 2
commit-message:
  prefix: chore
  include: scope
labels:
  - "type: dependency"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
