name: Set up Gradle build environment
description: Prepares environment for building with JDK and Gradle
inputs:
  run-release:
    description: 'Whether to run in release mode (true/false). In release mode, Gradle cache is not used.'
    required: false
    default: 'false'
  add-job-summary:
    description: 'Whether to add a job summary (always, never, on-failure).'
    required: false
    default: 'always'
  write-cache:
    description: 'Whether to write to the cache (true/false).'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Copy CI gradle.properties
      shell: bash
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Gradle without cache
      uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
      with:
        cache-disabled: ${{ inputs.run-release }}
        add-job-summary: ${{ inputs.add-job-summary }}
        cache-read-only: ${{ inputs.write-cache == 'false' || inputs.run-release == 'true' }}
