name: Markdown CI

on:
  pull_request:
    paths:
      - '**.md'
      - '.github/workflows/markdown.yml'

permissions:
  contents: read

jobs:
  markdown_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Cargo cache
        uses: actions-rust-lang/setup-rust-toolchain@ab6845274e2ff01cd4462007e1a9d9df1ab49f42  # v1.14.0

      - name: Install mdbook and extensions
        run: ./docs/install.sh

      - name: Setup Gradle environment
        uses: ./.github/actions/setup-gradle

      - name: Quality - Spotless Markdown Check
        run: ./gradlew spotlessFlexmarkCheck

      - name: Test mdbook docs
        run: mdbook test docs
